In [3]:
# Python version
import sys
print('Python: {}'.format(sys.version))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# matplotlib
import seaborn
print('seaborn: {}'.format(seaborn.__version__))
# matplotlib
import bokeh
print('bokeh: {}'.format(bokeh.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
scipy: 1.3.1
numpy: 1.16.5
matplotlib: 3.1.1
seaborn: 0.9.0
bokeh: 1.3.4
pandas: 0.25.1
sklearn: 0.21.3


In [5]:
from numpy import empty
A = empty([3,3])

print(A)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 3.557e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [9]:
import numpy as np

y = np.array([1,2,3])
x = np.array([2,3,4])
print(y + x)
print(y - x)
print(y / x)
print(y * x)

[3 5 7]
[-1 -1 -1]
[0.5        0.66666667 0.75      ]
[ 2  6 12]


# Python OS module

In [1]:
import os
os.getcwd()

'C:\\Users\\abhi0\\Documents\\JupyterNotebook'

In [2]:
cd ..

C:\Users\abhi0\Documents


In [4]:
os.chdir('C:\\Users\\abhi0\\Documents\\JupyterNotebook')
os.getcwd()

'C:\\Users\\abhi0\\Documents\\JupyterNotebook'

# Jupyter Notebook Hacks

In [1]:
# To get multiple outputs in the same cell

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Returns the variables present in the global space along with its type

%who

InteractiveShell	 


In [3]:
# Provides a list of all the commands given in the notebook

%history

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%who
%history


In [5]:
# Run profiler

#%prun < python statements>

Note:
1. Jupyter notebook provides a simple wrapper to run Python Profiler – %prun.
2. A profiler helps to analyze the code so that pain points can be optimized.
3. It provides the number of function calls and the execution time.
4. Other information provided is:
    1. ncalls – number of calls
    2. tottime – The total time spent in the given function (excluding time made in calls to sub-functions)
    3. percall – the quotient of tottime divided by ncalls
    4. cumtime –  the total time spent in this and all subfunctions (from invocation till exit)
    5. percall – the quotient of cumtime divided by primitive calls

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# 1
plt.figure(figsize=(16, 6))

# 2
fig_dims = (25, 8)
plt.figure(figsize=fig_dims)

# data = np.random.normal(0, 1, 3)
# array([-1.18878589,  0.59627021,  1.59895721])
# sns.boxplot(x=data);

<Figure size 1152x432 with 0 Axes>

<Figure size 1800x576 with 0 Axes>

<Figure size 1152x432 with 0 Axes>

<Figure size 1800x576 with 0 Axes>