# Create and Initialize NumPy Arrays

## To create NumPy arrays of different datatypes

In [1]:
# import numpy package
import numpy as np

In [2]:
# array(),dtype
a=np.array([1,2,3], dtype=np.int16)
print(a)
print(a.dtype)

[1 2 3]
int16


In [3]:
# arange() - creates an array with evenly spaced numbers between start,inclusive and end,exclusive
ar=np.arange(0,10,1,dtype=np.int32)
print(ar)
print(ar.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [4]:
# array(), dtype
b=np.array([1,2,3],dtype=np.float16)
print(b)
print(b.dtype)

print('\n')

# arange() - creates an array with evenly spaced numbers between start,inclusive and end,exclusive
br=np.arange(0,10,1,dtype=np.float64)
print(br)
print(br.dtype)

[1. 2. 3.]
float16


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


## To get the no. of axes, dimensions

In [5]:
# ndim()
print(np.ndim(a))
print(np.ndim(ar))
print(np.ndim(b))
print(np.ndim(br))

print('\n')

print(a.ndim)
print(ar.ndim)
print(b.ndim)
print(br.ndim)

1
1
1
1


1
1
1
1


In [6]:
# 2-D
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(np.ndim(c))
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]]
2
2


In [7]:
# 3-D
d=np.array([[[1,2],[3,4],[5,6]],[[11,12],[13,14],[15,16]]])
print(d)
print(np.ndim(d))
print(d.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 12]
  [13 14]
  [15 16]]]
3
3


## To get the No. of Axes and No. of elements in each Axis

In [8]:
# shape()
print(np.shape(a))
print(np.shape(b))
print(np.shape(c))
print(np.shape(d))

print('\n')

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print('\n')

print(d.shape[0])
print(d.shape[1])
print(d.shape[2])

(3,)
(3,)
(3, 2)
(2, 3, 2)


(3,)
(3,)
(3, 2)
(2, 3, 2)


2
3
2


## To create NumPy arrays using ones() and zeros()

In [9]:
zero=np.zeros((2,3))
print(zero)
print(zero.shape)

print('\n')

one=np.ones((2,3,2))
print(one)
print(one.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(2, 3, 2)


## Specify the dtype as the second argument to create array with specific datatype

In [10]:
zero=np.zeros((3,2,1),dtype=np.int16)
print(zero)
print(zero.shape)

print('\n')

one=np.ones((1,2,3),dtype=np.int16)
print(one)
print(one.shape)

print('\n')

one=np.ones((9),dtype=np.int16)
print(one)
print(one.shape)

[[[0]
  [0]]

 [[0]
  [0]]

 [[0]
  [0]]]
(3, 2, 1)


[[[1 1 1]
  [1 1 1]]]
(1, 2, 3)


[1 1 1 1 1 1 1 1 1]
(9,)


##  To create an evenly spaced sequence of float values in a specific interval - linspace()

In [11]:
arr=np.linspace(1,10,11,dtype=np.int32)
arr

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr=np.linspace(1,10,11,dtype=np.float32)
arr

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ],
      dtype=float32)

Note: Check the difference in the array created due to difference in datatype.

# Indexing and Slicing in NumPy Arrays

In [13]:
# Create an array with 10 elements
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [15]:
print(a[1:])

[1 2 3 4 5 6 7 8 9]


In [16]:
print(a[1:3])

[1 2]


In [17]:
print(a[1:-1])

[1 2 3 4 5 6 7 8]


In [18]:
print(a[:2])

[0 1]


In [19]:
print(a[::2])

[0 2 4 6 8]


In [20]:
print(a[1::2])

[1 3 5 7 9]


In [21]:
# Reverse the array
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [22]:
# The default start index for negative step sizes is -1
print(a[:1:-2])

[9 7 5 3]


In [23]:
print(a[-1:1:-2])

[9 7 5 3]


In [24]:
# Assignment of a value to an index
a[2]=12
a

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9])

In [25]:
# Assignment of a value to an extended slice
a[::2]=101
a

array([101,   1, 101,   3, 101,   5, 101,   7, 101,   9])

In [26]:
a = np.arange(16)

# converts array a from a single-axis array print(a)
a = a.reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
print(a[:, 1])

[ 1  5  9 13]


In [28]:
print(a[1, :])

[4 5 6 7]


In [29]:
print(a[1, ::2])

[4 6]


In [30]:
print(a[:, :-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [31]:
print(a[:-1]) # Same as a[:-1, :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
b = np.arange(3**3)
b = b.reshape((3,3,3))
print(b)
print(b[0, ..., 0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[0 3 6]


In [33]:
# Incase of only 2 or 1 arguments, the indexes are considered in 3d,2d,1d axis.
print(b[:, 1])

[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


In [34]:
print(b[...,:, 1])

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [35]:
print(b[:,:, 1])

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [36]:
''' Specify a boolean array with exactly the same shape. If
the boolean value at position (i,j) is True, the element
will be selected, otherwise not '''

' Specify a boolean array with exactly the same shape. If\nthe boolean value at position (i,j) is True, the element\nwill be selected, otherwise not '

In [37]:
c = np.arange(9)
c = c.reshape((3,3))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
b = np.array(
[[ True, False, False],
[ False, True, False],
[ False, False, True]])
print(c[b])

[0 4 8]


Note: Only those elements from array 'c' is selected for which the boolean value in array 'b' at respective position (i,j) is True.

## Exercise I
1.  Extracting Array Dimensionality       - ndim
2.  Accessing Array Shape                 - shape
3.  Restructuring Array                   - reshape()
4.  Averaging 1D Arrays                   - average()
5.  Working with Not a Number             - np.NaN is checked with np.isnan()
6.  Creating Numerical Sequences          - np.arange()
7.  Creating Numerical Intervals          - np.linspace()
8.  Initializing Multi-Dimensional Arrays - 
9.  Revisiting Linear Algebra             - np.eyes()
10. Understanding the Hadamard Product    - 
11. Broadcasting                          -
12. Practicing Simple Indexing            - 
13. The Boolean Indexing Trick            -
14. Slicing Matrices Like Paper           -
15. Simple Array Logic                    - comparison operators directly on NumPy arrays
16. Mastering Slice Assignments           -
17. Sorting an Array (Part 1)             - sort()
18. Sorting an Array (Part 2)             - argsort()
19. Computing Array Element Differences   - diff()
20. Computing Array of Cumulative Sums    - cumsum()

In [39]:
# 5. Working with Not a Number             - np.NaN is checked with np.isnan()

import numpy as np
# Students' quiz results.
# NaN for students that were absent.
data = np.array([10, 3, np.NaN, 7, np.NaN, 5])
print(data)
students_present = 0
students_absent = 0
for result in data:
    if result == np.NaN:
        students_absent += 1
    else:
        students_present += 1
print('''Results with '==' check : Students Present -''',students_present)

# Using np.isnan()
students_present = 0
students_absent = 0
for result in data:
    if np.isnan(result):
        students_absent += 1
    else:
        students_present += 1
print('''Results with 'np.isnan()' check : Students Present -''',students_present)

[10.  3. nan  7. nan  5.]
Results with '==' check : Students Present - 6
Results with 'np.isnan()' check : Students Present - 4


In [40]:
# 7. Creating Numerical Intervals          - np.linspace()

import numpy as np

year = np.linspace(0, 365, 366)

print(int(year[-1] - year[-2]))

1


In [41]:
# 8. Initializing Multi-Dimensional Arrays - 

import numpy as np
n = 100 # dimensionality
W = np.zeros((n,n))

for i in range(len(W)):
    W[i][i] = 2

X = np.ones((n,n))
Y = W * X

print(int(Y[-1][-1]))

2


In [42]:
Y

array([[2., 0., 0., ..., 0., 0., 0.],
       [0., 2., 0., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 2., 0., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 0., 2.]])

In [43]:
# 9. Revisiting Linear Algebra             - np.eyes()

import numpy as np

# dimensionality
n = 10
W = np.zeros((n, n))

for i in range(len(W)):
    W[i][i] = 2

# Create nxn matrix
M = np.eye(n, k=0)

S = W + 3 * M
print(S[-1][-1])
print(int(S[-1][-1]))
print(S)

5.0
5
[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [44]:
# Demonstration of usage of eye()
# Create nxn matrix
AZ = np.eye(n, k=0)
AZ

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
# Create nxn matrix
BY = np.eye(n, k=1)
BY

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
# Create nxn matrix
CX = np.eye(n, k=-1)
CX

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

Note: 
1. eye() creates an array with diagonal as 1.
2. k changes the position of the diagonal.

In [47]:
# 10. Understanding the Hadamard Product    -
# The multiplication operator ‘*’ creates a new matrix by multiplying the two values at position (i,j) of the two matrices. We call this the Hadamard Product.

import numpy as np

# salary in ($1000) [2015, 2016, 2017]
dataScientist = [133, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]

# Salary matrix
S = np.array([dataScientist,
              productManager,
              designer,
              softwareEngineer])

# Salary increase matrix
I = np.array([[1.1, 1.2, 1.3],
              [1.0, 1.0, 1.0],
              [0.9, 0.8, 0.7],
              [1.1, 1.1, 1.1]])

# Updated salary
S2 = S * I
print(S2[2][0] > S[2][0])
print(S2[2][0])
print(S[2][0])

False
106.2
118


In [48]:
# 11. Broadcasting

import numpy as np

# salary in ($1000) [2015, 2016, 2017]
dataScientist = [130, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]

A = np.array([dataScientist,
              productManager,
              designer,
              softwareEngineer])

# salary raise for data scientists
B = np.ones((4,1))
B[0] = 1.1

# new salary calculation
C = A * B

print(C[0][0])
print(int(C[0][0]))
print(C)


143.0
143
[[143.  145.2 150.7]
 [127.  140.  145. ]
 [118.  118.  127. ]
 [129.  131.  137. ]]


Note:
1. Please note that the *-operator calculates the Hadamard Product and not standard matrix multiplication. 
2. In fact,it would not even be possible to multiply a (4,3) matrix with a (4,1) vector because you can only multiply (n,m) with (m,o) matrices.
3. Instead, NumPy uses the useful feature of broadcasting.
4. In other words, it automatically fixes the shapes of incompatible arrays by expanding the smaller one.
5. In the above example, NumPy creates a (virtual) matrix consisting of three times the column vector B.

In [49]:
# 12. Practicing Simple Indexing            - 

import numpy as np
# air quality index AQI data
hong_kong = np.array([ 42, 40, 41, 43, 44, 43 ])
new_york = np.array([ 30, 31, 29, 29, 29, 30 ])
montreal = np.array([ 11, 11, 12, 13, 11, 12 ])

hk_mean = (hong_kong[0] +hong_kong[-1]) / 2.0
ny_mean = (new_york[1] +new_york[-3]) / 2.0
m_mean = (montreal[1] +montreal[-0]) / 2.0

print(hk_mean)
print(ny_mean)
print(m_mean)

# to understand behaviour of index [-0]
# print(montreal[0])
# print(montreal[-0])

42.5
30.0
11.0


In [50]:
# 13. The Boolean Indexing Trick            -

import numpy as np

years = np.array([[ 2000, 2001, 2002],
                  [ 2003, 2004, 2005],
                  [ 2006, 2007, 2008]])

leap_years_indices = np.array([[ True, False, False],
                               [ False, True, True],
                               [ False, False, True]])

# creation of an array with leap years
leap_years=years[leap_years_indices]
print(leap_years)
# checking the dimension of leap_years
print(leap_years.ndim)

print(years[leap_years_indices][-1])
print(years[leap_years_indices])

[2000 2004 2005 2008]
1
2008
[2000 2004 2005 2008]


In [51]:
# 14. Slicing Matrices Like Paper           -

import numpy as np

# Prints out a multi dimensional numpy array as,! one line
# Example: np.array([['a'], ['b'], ['c']]) -->,! abc

def glow(snippet):
    for c in snippet:
        print(*c, end='')
        
newspaper = np.array([[' ', 'a', 'p', 'p'],
                      ['b', 'a', 'n', 'a'],
                      ['t', 'o', 'm', 't'],
                      ['c', 'u', 'c', 'a'],
                      ['l', 'e', 's', 'e'],
                      ['p', 'r', 'e', 's'],
                      ['c', 'a', 'r', 's'],
                      ['y', 'e', 'a', 'r']])

snippet0 = newspaper[2:5, -1][::-1] # added
snippet1 = newspaper[2:5, -1:][::-1]
snippet2 = newspaper[0, :]
snippet3 = newspaper[0:1, :] # added
snippet4 = newspaper[4, :-1]

print(snippet0)
print(snippet0.ndim)
print(snippet1)
print(snippet1.ndim)
print(snippet2)
print(snippet2.ndim)
print(snippet3)
print(snippet3.ndim)
print(snippet4)
print(snippet4.ndim)

glow(snippet1)
glow(snippet2)
glow(snippet4)

['e' 'a' 't']
1
[['e']
 ['a']
 ['t']]
2
[' ' 'a' 'p' 'p']
1
[[' ' 'a' 'p' 'p']]
2
['l' 'e' 's']
1
eat apples

Note:
It is very important to notice how a ':' produces a subtle difference in the dimension of the arrays.
For example, snippet0 and snippet1 are 1d and 2d with almost the same slicing except a ':'.
Similarly, difference between snippet2 and snippet3 is worth-noting.

In [52]:
# 15. Simple Array Logic                    - comparison operators directly on NumPy arrays

import numpy as np

# popular instagram accounts
# (millions followers)
inst = [232, #"@instagram"
        133, #"@selenagomez"
        59, #"@victoriassecret"
        120, #"@cristiano"
        111, #"@beyonce"
        76] #"@nike"

inst = np.array(inst)

superstars = inst > 100

print(superstars)
print(superstars[0])
print(superstars[2])

[ True  True False  True  True False]
True
False


Note:
1. Using comparison operators directly on NumPy arrays, the result is an equally-sized NumPy array with Boolean values.
2. Each Boolean value in cell (i,j) indicates whether the comparison evaluates to True for its respective value in cell (i,j) of the original array.

In [53]:
# 16. Mastering Slice Assignments           -

import numpy as np

# The fibonacci series
F = np.array([0, 1, 1, 2, 3, 5, 8])
F[::3] = 0

print(sum(F[:4]))
#print(F)

2


In [54]:
# 17. Sorting an Array (Part 1)             - sort()

import numpy as np

# Quiz scores for different students
scores = np.array([7, 6, 8, 5, 9])
scores = np.sort(scores)
scores = scores[::-1]
print(scores[-2])

6


Note:
sort() is used to sort array, default is ascending. The statement 'scores = scores[::-1]' re-assigns the reversed array into scores.

In [55]:
# 18. Sorting an Array (Part 2)             - argsort()

import numpy as np

# Sensor IDs and the corresponding sensor values
ids = [56, 61, 33, 17, 82]
values = np.array([10, 6, 8, 7, 9])

indices = np.argsort(values)

print(indices)
print(ids[indices[2]])

[1 3 2 4 0]
33


Note:
1. argsort() function, sort the values in ascending order.
2. Instead of returning the sorted array, this function returns the indices of elements from the original values array in the order in which they occur in the sorted array.
3. Observe the indices array.

In [56]:
def takeSecond(elem):
    return elem[1]
lst=np.array([c for c in zip(ids,values)])
print(lst)
lst=np.sort(lst,key=takeSecond)

[[56 10]
 [61  6]
 [33  8]
 [17  7]
 [82  9]]


TypeError: sort() got an unexpected keyword argument 'key'

i want to sort the first array based on the values from second array. for list it can be done through key= option in sort()

In [57]:
# 19. Computing Array Element Differences   - diff()

import numpy as np

# Fibonacci Sequence with first 8 numbers
fibs = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21])

diff_fibs = np.diff(fibs)

print(diff_fibs)
print(diff_fibs[4])

[1 0 1 1 2 3 5 8]
2


Note:
1. diff() function calculates the difference between consecutive numbers in a NumPy array.
2. These differences can be stored as another array.
3. Since, diff() returns an array of differences, this array’s size is smaller than the length of the input array by 1 element.

In [58]:
# 20. Computing Array of Cumulative Sums    - cumsum()

import numpy as np

# Per-day charity donations in thousands of dollars received in a charity compaign
donations = np.array([2, 3, 2.5, 3.5, 4, 3.5])
cum_donations = np.cumsum(donations)

print(cum_donations)
print(cum_donations[-4])

[ 2.   5.   7.5 11.  15.  18.5]
7.5


Note: NumPy’s cumsum() function generate the cumulative sum of array.

## Exercise II
1.  Calculating 1D Dot Product            - np.dot()
2.  Multiplying 2D Matrices               - @, np.matmul()
3.  Enhancing Vector Operations           - 
4.  Linear Algebra Made Simple            - 
5.  Revisiting Average                    - np.average()
6.  Reshaping 1D Arrays                   - reshape()
7.  Averaging 2D Arrays                   - np.average()
8.  Weighted Averaging Along Axes         - 
9.  Calculating 1D Variance               - np.var()
10. Axis Variance of a 2D Array           - np.var()
11. 1D Axis Standard Deviation            -

In [60]:
# 1.  Calculating 1D Dot Product            - np.dot()

import numpy as np

# simple regression model
W = np.array([0.7, 0.2, 0.1])

# Google stock prices (in US-$) [today, yesterday, 2 days ago]
x = np.array([1131, 1142, 1140])

# prediction
y = np.dot(W, x)

print(y)
print(x[0])
# do we expect growing prices?
if y > x[0]:
    print("buy")
else:
    print("sell")

1134.1
1131
buy


Note:
1. The stock prices of the last three days are 1132, 1142 and 1140.
2. The predicted stock price for the next day is y = 0.7 * 1132 + 0.2 * 1142 + 0.1 * 1140 = 1134.8.

In [66]:
# 2.  Multiplying 2D Matrices               - @, np.matmul()

import numpy as np
# graphics data
a = [[1, 1],[1, 0]]
a = np.array(a)

# stretch vectors
b = [[2, 0],[0, 2]]
b = np.array(b)

c = a @ b
d = np.matmul(a,b)

print(c)
print(d)
print((c == d)[0,0])

[[2 2]
 [2 0]]
[[2 2]
 [2 0]]
True


Note:
1. NumPy supports two syntaxes for matrix multiplication: the matmul function and the @ operator.
2. The * operator performs element-wise matrix multiplication and is therefore different.

In [67]:
# 3.  Enhancing Vector Operations           - 

import numpy as np

# Two points in 3D space
a = np.array([5, -3, 2])
b = np.array([1, 0, 2])

c = b - a
vec_len = np.sqrt(sum(c ** 2))

print(int(vec_len))

5


In [68]:
# 4.  Linear Algebra Made Simple            - 

import numpy as np

# Two vectors in 3D space
a = np.array([5, -3, 2])
b = np.array([1, 0, 2])

c = np.cross(a, b)

scalar_prod = np.dot(a, c)

print(c)
print(scalar_prod)

[-6 -8  3]
0


In [69]:
# 5.  Revisiting Average                    - average()

import numpy as np

# Goals in five matches
goals_brazil = np.array([1,2,3,1,2])
goals_germany = np.array([1,0,1,2,0])

br = np.average(goals_brazil)
ge = np.average(goals_germany)

print(br>ge)

True


In [70]:
# 6.  Reshaping 1D Arrays                   - np.reshape()

import numpy as np

def makeTwoDim(x):
    if len(x.shape)==1:
        x = x.reshape(len(x) // 2, 2)
        return x

# apple stock prices (May 2018)
prices = [ 189, 186, 186, 188,
           187, 188, 188, 186,
           188, 188, 187, 186 ]

data = np.array(prices)
data = makeTwoDim(data)

print(np.average(data[-1]))

186.5


Note:
1. It creates a one-dimensional NumPy array from raw price data. 
2. Note that the shape property of an ndimensional NumPy array is a tuple with n elements.
3. Thus, a one-dimensional NumPy array has a shape property of length one.
4. The function makeTwoDim(x) uses this to detect onedimensional NumPy arrays.
5. Then, it transforms these into two-dimensional arrays using the reshape function.

In [71]:
# 7.  Averaging 2D Arrays                   - np.average()

import numpy as np

# stock prices (3x per day) [morning, midday, evening]
solar_x = np.array( [[2, 3, 4], # day 1
                    [2, 2, 5]]) # day 2

print(np.average(solar_x))

3.0


Note:
1. The average function of the NumPy library, applied to a 1D NumPy array, returns the average of the array values. 
2. When applied to a 2D NumPy array, NumPy simply flattens the array.
3. The result is the average of the flattened 1D array.

In [72]:
# 8.  Weighted Averaging Along Axes         - 

import numpy as np
# daily stock prices [morning, midday, evening]
solar_x = np.array([[2, 3, 4], # today
                   [2, 2, 5]]) # yesterday

# midday - weighted average
print(np.average(solar_x, axis=0,weights=[3/4, 1/4])[1])

2.75
