# Create and Initialize NumPy Arrays

## To create NumPy arrays of different datatypes

In [2]:
# import numpy package
import numpy as np

In [3]:
# array(),dtype
a=np.array([1,2,3], dtype=np.int16)
print(a)
print(a.dtype)

[1 2 3]
int16


In [4]:
# arange() - creates an array with evenly spaced numbers between start,inclusive and end,exclusive
ar=np.arange(0,10,1,dtype=np.int32)
print(ar)
print(ar.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [5]:
# array(), dtype
b=np.array([1,2,3],dtype=np.float16)
print(b)
print(b.dtype)

print('\n')

# arange() - creates an array with evenly spaced numbers between start,inclusive and end,exclusive
br=np.arange(0,10,1,dtype=np.float64)
print(br)
print(br.dtype)

[1. 2. 3.]
float16


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


## To get the no. of axes, dimensions

In [6]:
# ndim()
print(np.ndim(a))
print(np.ndim(ar))
print(np.ndim(b))
print(np.ndim(br))

print('\n')

print(a.ndim)
print(ar.ndim)
print(b.ndim)
print(br.ndim)

1
1
1
1


1
1
1
1


In [7]:
# 2-D
c=np.array([[1,2],[3,4],[5,6]])
print(c)
print(np.ndim(c))
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]]
2
2


In [8]:
# 3-D
d=np.array([[[1,2],[3,4],[5,6]],[[11,12],[13,14],[15,16]]])
print(d)
print(np.ndim(d))
print(d.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 12]
  [13 14]
  [15 16]]]
3
3


## To get the No. of Axes and No. of elements in each Axis

In [9]:
# shape()
print(np.shape(a))
print(np.shape(b))
print(np.shape(c))
print(np.shape(d))

print('\n')

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

print('\n')

print(d.shape[0])
print(d.shape[1])
print(d.shape[2])

(3,)
(3,)
(3, 2)
(2, 3, 2)


(3,)
(3,)
(3, 2)
(2, 3, 2)


2
3
2


## To create NumPy arrays using ones() and zeros()

In [10]:
zero=np.zeros((2,3))
print(zero)
print(zero.shape)

print('\n')

one=np.ones((2,3,2))
print(one)
print(one.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(2, 3, 2)


## Specify the dtype as the second argument to create array with specific datatype

In [11]:
zero=np.zeros((3,2,1),dtype=np.int16)
print(zero)
print(zero.shape)

print('\n')

one=np.ones((1,2,3),dtype=np.int16)
print(one)
print(one.shape)

print('\n')

one=np.ones((9),dtype=np.int16)
print(one)
print(one.shape)

[[[0]
  [0]]

 [[0]
  [0]]

 [[0]
  [0]]]
(3, 2, 1)


[[[1 1 1]
  [1 1 1]]]
(1, 2, 3)


[1 1 1 1 1 1 1 1 1]
(9,)


##  To create an evenly spaced sequence of float values in a specific interval - linspace()

In [40]:
arr=np.linspace(1,10,11,dtype=np.int32)
arr

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr=np.linspace(1,10,11,dtype=np.float32)
arr

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ],
      dtype=float32)

Note: Check the difference in the array created due to difference in datatype.

# Indexing and Slicing in NumPy Arrays

In [12]:
# Create an array with 10 elements
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(a[1:])

[1 2 3 4 5 6 7 8 9]


In [15]:
print(a[1:3])

[1 2]


In [16]:
print(a[1:-1])

[1 2 3 4 5 6 7 8]


In [17]:
print(a[:2])

[0 1]


In [19]:
print(a[::2])

[0 2 4 6 8]


In [20]:
print(a[1::2])

[1 3 5 7 9]


In [22]:
# Reverse the array
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [23]:
# The default start index for negative step sizes is -1
print(a[:1:-2])

[9 7 5 3]


In [25]:
print(a[-1:1:-2])

[9 7 5 3]


In [27]:
# Assignment of a value to an index
a[2]=12
a

array([ 0,  1, 12,  3,  4,  5,  6,  7,  8,  9])

In [28]:
# Assignment of a value to an extended slice
a[::2]=101
a

array([101,   1, 101,   3, 101,   5, 101,   7, 101,   9])

In [45]:
a = np.arange(16)

# converts array a from a single-axis array print(a)
a = a.reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
print(a[:, 1])

[ 1  5  9 13]


In [47]:
print(a[1, :])

[4 5 6 7]


In [48]:
print(a[1, ::2])

[4 6]


In [49]:
print(a[:, :-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [50]:
print(a[:-1]) # Same as a[:-1, :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
b = np.arange(3**3)
b = b.reshape((3,3,3))
print(b)
print(b[0, ..., 0])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[0 3 6]


In [53]:
# Incase of only 2 or 1 arguments, the indexes are considered in 3d,2d,1d axis.
print(b[:, 1])

[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


In [54]:
print(b[...,:, 1])

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [56]:
print(b[:,:, 1])

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [57]:
''' Specify a boolean array with exactly the same shape. If
the boolean value at position (i,j) is True, the element
will be selected, otherwise not '''

' Specify a boolean array with exactly the same shape. If\nthe boolean value at position (i,j) is True, the element\nwill be selected, otherwise not '

In [58]:
c = np.arange(9)
c = c.reshape((3,3))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [60]:
b = np.array(
[[ True, False, False],
[ False, True, False],
[ False, False, True]])
print(c[b])

[0 4 8]


Note: Only those elements from array 'c' is selected for which the boolean value in array 'b' at respective position (i,j) is True.

## Re-collect
1. Extracting Array Dimensionality - ndim
2. Accessing Array Shape           - shape
3. Restructuring Array             - reshape()
4. Averaging 1D Arrays             - average()
5. Working with Not a Number       - np.NaN is checked with np.isnan()

In [77]:
import numpy as np
# Students' quiz results.
# NaN for students that were absent.
data = np.array([10, 3, np.NaN, 7, np.NaN, 5])
print(data)
students_present = 0
students_absent = 0
for result in data:
    if result == np.NaN:
        students_absent += 1
    else:
        students_present += 1
print('''Results with '==' check : Students Present -''',students_present)

# Using np.isnan()
students_present = 0
students_absent = 0
for result in data:
    if np.isnan(result):
        students_absent += 1
    else:
        students_present += 1
print('''Results with 'np.isnan()' check : Students Present -''',students_present)

[10.  3. nan  7. nan  5.]
Results with '==' check : Students Present - 6
Results with 'np.isnan()' check : Students Present - 4
